"""
Risk Swarm: Multi-Agent System for Autonomous Risk Management
=============================================================

Implements a hierarchical swarm of specialized agents that collaborate
to monitor, analyze, and manage portfolio risk autonomously.

Architecture:
- Architect: Central orchestrator breaking down mandates into sub-goals
- Analysts: Domain-specific agents (Vol, Credit, Macro, etc.)
- Judge: Non-LLM compliance firewall validating all actions

Author: BXMA Quant Team
Date: January 2026
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any, Callable
import uuid

from bxma.agents.react import (
    ReActAgent,
    AgentRole,
    AgentConfig,
    AgentState,
    FinancialTool,
    Thought,
    Action,
    Observation,
)


class SwarmMode(Enum):
    """Operating mode for the risk swarm."""
    ADVISORY = auto()      # Agents suggest, humans execute
    SEMI_AUTO = auto()     # Agents execute small trades, humans approve large
    AUTONOMOUS = auto()    # Full automation (with Judge oversight)


@dataclass
class SwarmConfig:
    """Configuration for the Risk Swarm."""
    
    mode: SwarmMode = SwarmMode.ADVISORY
    
    # Agent configuration
    max_concurrent_agents: int = 10
    agent_timeout_seconds: float = 60.0
    
    # Thresholds for semi-auto mode
    max_auto_trade_value: float = 1_000_000  # $1M
    max_auto_position_change: float = 0.01   # 1% of portfolio
    
    # Communication
    broadcast_observations: bool = True
    share_working_memory: bool = True
    
    # Safety
    require_consensus: bool = False  # Multiple agents must agree
    consensus_threshold: float = 0.7  # 70% agreement needed
    
    # Audit
    log_all_communications: bool = True
    explain_all_decisions: bool = True


@dataclass
class SwarmMessage:
    """Message passed between agents in the swarm."""
    
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    sender: str = ""
    receiver: str = ""  # Empty = broadcast
    message_type: str = ""  # "observation", "request", "response", "alert"
    content: Any = None
    priority: int = 0  # Higher = more urgent
    timestamp: datetime = field(default_factory=datetime.now)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "sender": self.sender,
            "receiver": self.receiver,
            "message_type": self.message_type,
            "content": str(self.content)[:1000],
            "priority": self.priority,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class RiskNarrative:
    """
    A structured risk narrative generated by an analyst agent.
    
    Captures the "story" behind a risk condition.
    """
    
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    agent_id: str = ""
    domain: str = ""  # "volatility", "credit", "macro", "liquidity"
    
    # Narrative content
    headline: str = ""
    summary: str = ""
    supporting_data: dict[str, Any] = field(default_factory=dict)
    
    # Risk assessment
    severity: float = 0.0  # 0-1 scale
    confidence: float = 0.0
    recommended_actions: list[str] = field(default_factory=list)
    
    # Metadata
    timestamp: datetime = field(default_factory=datetime.now)
    sources: list[str] = field(default_factory=list)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "agent_id": self.agent_id,
            "domain": self.domain,
            "headline": self.headline,
            "summary": self.summary,
            "severity": self.severity,
            "confidence": self.confidence,
            "recommended_actions": self.recommended_actions,
            "timestamp": self.timestamp.isoformat(),
        }


class JudgeAgent:
    """
    Non-LLM Compliance Firewall
    
    This is a deterministic agent that validates all proposed actions
    against hard-coded compliance rules. It acts as a safety net,
    preventing LLM agents from executing prohibited actions.
    
    Unlike other agents, the Judge uses NO machine learning - only
    explicit, auditable rules.
    """
    
    def __init__(self):
        self.rules: list[Callable[[Action], tuple[bool, str]]] = []
        self.restricted_symbols: set[str] = set()
        self.max_position_sizes: dict[str, float] = {}
        self.trading_windows: list[tuple[int, int]] = [(9, 16)]  # 9am-4pm
        
        self._initialize_default_rules()
    
    def _initialize_default_rules(self):
        """Initialize default compliance rules."""
        
        # Rule 1: No trading restricted securities
        def check_restricted(action: Action) -> tuple[bool, str]:
            if action.tool_name in ["execute_trade", "propose_hedge"]:
                symbols = action.parameters.get("symbols", [])
                restricted = set(symbols) & self.restricted_symbols
                if restricted:
                    return False, f"Trading restricted securities: {restricted}"
            return True, ""
        self.rules.append(check_restricted)
        
        # Rule 2: Position size limits
        def check_position_size(action: Action) -> tuple[bool, str]:
            if action.tool_name == "execute_trade":
                for symbol, size in action.parameters.get("positions", {}).items():
                    max_size = self.max_position_sizes.get(symbol, 0.10)
                    if abs(size) > max_size:
                        return False, f"Position size {size} exceeds limit {max_size} for {symbol}"
            return True, ""
        self.rules.append(check_position_size)
        
        # Rule 3: Trading hours
        def check_trading_hours(action: Action) -> tuple[bool, str]:
            if action.tool_name == "execute_trade":
                hour = datetime.now().hour
                in_window = any(start <= hour < end for start, end in self.trading_windows)
                if not in_window:
                    return False, f"Trading outside permitted hours"
            return True, ""
        self.rules.append(check_trading_hours)
        
        # Rule 4: No short selling certain assets
        def check_short_selling(action: Action) -> tuple[bool, str]:
            if action.tool_name == "execute_trade":
                positions = action.parameters.get("positions", {})
                for symbol, size in positions.items():
                    if size < 0 and symbol.startswith("ETF_"):  # No shorting ETFs
                        return False, f"Short selling prohibited for {symbol}"
            return True, ""
        self.rules.append(check_short_selling)
    
    def add_rule(self, rule: Callable[[Action], tuple[bool, str]]):
        """Add a custom compliance rule."""
        self.rules.append(rule)
    
    def add_restricted_symbol(self, symbol: str):
        """Add a symbol to the restricted list."""
        self.restricted_symbols.add(symbol)
    
    def set_position_limit(self, symbol: str, max_size: float):
        """Set maximum position size for a symbol."""
        self.max_position_sizes[symbol] = max_size
    
    def validate(self, action: Action) -> tuple[bool, list[str]]:
        """
        Validate an action against all compliance rules.
        
        Returns:
            Tuple of (is_valid, list_of_violations)
        """
        violations = []
        
        for rule in self.rules:
            try:
                valid, message = rule(action)
                if not valid:
                    violations.append(message)
            except Exception as e:
                violations.append(f"Rule evaluation error: {str(e)}")
        
        return len(violations) == 0, violations
    
    def get_approval_status(self, action: Action) -> dict:
        """
        Get detailed approval status for an action.
        
        This is logged for audit purposes.
        """
        valid, violations = self.validate(action)
        
        return {
            "action": action.to_dict(),
            "approved": valid,
            "violations": violations,
            "timestamp": datetime.now().isoformat(),
            "judge_id": "COMPLIANCE_JUDGE_V1",
        }


class ArchitectAgent:
    """
    Central Orchestrator Agent
    
    Breaks down high-level mandates into sub-goals and delegates
    to specialist agents. Synthesizes results into actionable recommendations.
    """
    
    def __init__(
        self,
        config: AgentConfig,
        llm_interface: Callable[[str], str] | None = None,
    ):
        self.config = config
        self.llm = llm_interface or self._default_llm
        self.agent_id = f"architect_{str(uuid.uuid4())[:4]}"
        
        # Sub-agents managed by this architect
        self.analysts: dict[str, "AnalystAgent"] = {}
        self.active_tasks: dict[str, dict] = {}
    
    def _default_llm(self, prompt: str) -> str:
        """Default LLM placeholder."""
        return f"Orchestrating: {prompt[:100]}..."
    
    def decompose_mandate(self, mandate: str) -> list[dict]:
        """
        Break down a high-level mandate into sub-goals.
        
        Example:
            Mandate: "Reduce portfolio volatility exposure"
            Sub-goals:
                - Analyze current volatility exposure by sector
                - Identify high-vol positions exceeding limits
                - Propose hedging strategies
                - Validate with compliance
        """
        prompt = f"""You are the Architect agent. Break down this mandate into specific sub-goals:

Mandate: {mandate}

For each sub-goal, specify:
1. A clear objective
2. Which specialist should handle it (volatility, credit, macro, execution)
3. Priority (1-5, 1=highest)
4. Dependencies on other sub-goals

Format as JSON array."""
        
        response = self.llm(prompt)
        
        # Parse response (with fallback)
        try:
            # Extract JSON from response
            import re
            json_match = re.search(r'\[.*\]', response, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
        except:
            pass
        
        # Fallback decomposition
        return [
            {"objective": "Analyze current state", "specialist": "general", "priority": 1, "dependencies": []},
            {"objective": "Identify risk factors", "specialist": "volatility", "priority": 2, "dependencies": [0]},
            {"objective": "Propose actions", "specialist": "execution", "priority": 3, "dependencies": [0, 1]},
        ]
    
    def synthesize_results(self, results: list[dict]) -> RiskNarrative:
        """
        Synthesize results from multiple analysts into a coherent narrative.
        """
        prompt = f"""Synthesize these analyst findings into a coherent risk narrative:

{json.dumps(results, indent=2)}

Provide:
1. Headline (one sentence)
2. Summary (2-3 sentences)
3. Severity (0-1)
4. Top 3 recommended actions"""
        
        response = self.llm(prompt)
        
        return RiskNarrative(
            agent_id=self.agent_id,
            domain="multi-domain",
            headline=response[:100],
            summary=response[:500],
            severity=0.5,  # Would be extracted from response
            confidence=0.8,
            recommended_actions=["Review volatility exposure", "Consider hedging", "Monitor closely"],
        )
    
    async def orchestrate(self, mandate: str) -> RiskNarrative:
        """
        Main orchestration loop.
        
        1. Decompose mandate into sub-goals
        2. Dispatch to specialist agents
        3. Collect and synthesize results
        4. Generate final narrative
        """
        # Decompose
        sub_goals = self.decompose_mandate(mandate)
        
        # Dispatch (would be async in production)
        results = []
        for goal in sub_goals:
            specialist = goal.get("specialist", "general")
            if specialist in self.analysts:
                analyst = self.analysts[specialist]
                result = await analyst.analyze(goal["objective"])
                results.append(result)
        
        # Synthesize
        narrative = self.synthesize_results(results)
        
        return narrative


class AnalystAgent:
    """
    Domain-Specific Analyst Agent
    
    Monitors a specific domain (volatility, credit, macro, etc.)
    and generates risk narratives.
    """
    
    def __init__(
        self,
        domain: str,
        config: AgentConfig,
        tools: dict[str, FinancialTool],
        llm_interface: Callable[[str], str] | None = None,
    ):
        self.domain = domain
        self.config = config
        self.tools = tools
        self.llm = llm_interface or self._default_llm
        self.agent_id = f"analyst_{domain}_{str(uuid.uuid4())[:4]}"
        
        # Create underlying ReAct agent
        self.react_agent = ReActAgent(
            role=AgentRole.ANALYST,
            config=config,
            tools=tools,
            llm_interface=llm_interface,
        )
    
    def _default_llm(self, prompt: str) -> str:
        """Default LLM placeholder."""
        return f"Analyzing {self.domain}: {prompt[:100]}..."
    
    async def analyze(self, objective: str) -> dict:
        """
        Perform domain-specific analysis.
        
        Returns structured findings.
        """
        goal = f"As a {self.domain} specialist, {objective}"
        state = self.react_agent.run(goal)
        
        return {
            "agent_id": self.agent_id,
            "domain": self.domain,
            "objective": objective,
            "findings": state.final_answer or "Analysis incomplete",
            "confidence": 0.8,
            "trajectory_length": state.iteration,
        }
    
    def generate_narrative(self, data: dict) -> RiskNarrative:
        """Generate a risk narrative from analysis data."""
        prompt = f"""As a {self.domain} analyst, generate a risk narrative from this data:

{json.dumps(data, indent=2)}

Include headline, summary, severity (0-1), and recommended actions."""
        
        response = self.llm(prompt)
        
        return RiskNarrative(
            agent_id=self.agent_id,
            domain=self.domain,
            headline=f"{self.domain.title()} Risk Alert",
            summary=response[:500],
            severity=0.5,
            confidence=0.8,
            supporting_data=data,
        )


class RiskSwarm:
    """
    Main Risk Swarm orchestrating multiple agents.
    
    The swarm continuously monitors portfolio risk and generates
    actionable insights through coordinated multi-agent collaboration.
    """
    
    def __init__(
        self,
        config: SwarmConfig,
        tools: dict[str, FinancialTool],
        llm_interface: Callable[[str], str] | None = None,
    ):
        self.config = config
        self.tools = tools
        self.llm = llm_interface
        
        # Initialize agents
        self.architect = ArchitectAgent(
            config=AgentConfig(),
            llm_interface=llm_interface,
        )
        
        self.judge = JudgeAgent()
        
        # Specialist analysts
        self.analysts: dict[str, AnalystAgent] = {}
        for domain in ["volatility", "credit", "macro", "liquidity"]:
            self.analysts[domain] = AnalystAgent(
                domain=domain,
                config=AgentConfig(),
                tools=tools,
                llm_interface=llm_interface,
            )
        
        # Register analysts with architect
        self.architect.analysts = self.analysts
        
        # Message queue
        self.message_queue: list[SwarmMessage] = []
        
        # Audit log
        self.audit_log: list[dict] = []
    
    def broadcast(self, message: SwarmMessage):
        """Broadcast a message to all agents."""
        self.message_queue.append(message)
        
        if self.config.log_all_communications:
            self.audit_log.append(message.to_dict())
    
    async def process_mandate(self, mandate: str) -> tuple[RiskNarrative, list[Action]]:
        """
        Process a high-level risk mandate.
        
        Returns:
            Tuple of (narrative, proposed_actions)
        """
        # Architect orchestrates
        narrative = await self.architect.orchestrate(mandate)
        
        # Extract proposed actions
        proposed_actions = []
        for action_desc in narrative.recommended_actions:
            action = Action(
                tool_name="propose_hedge",
                parameters={"description": action_desc},
                rationale=narrative.summary,
            )
            proposed_actions.append(action)
        
        # Validate with Judge
        approved_actions = []
        for action in proposed_actions:
            approval = self.judge.get_approval_status(action)
            self.audit_log.append(approval)
            
            if approval["approved"]:
                approved_actions.append(action)
        
        return narrative, approved_actions
    
    async def continuous_monitoring(self, callback: Callable[[RiskNarrative], None]):
        """
        Run continuous risk monitoring loop.
        
        Periodically checks each domain and generates narratives.
        """
        while True:
            for domain, analyst in self.analysts.items():
                try:
                    # Simulate getting current data
                    data = {"domain": domain, "timestamp": datetime.now().isoformat()}
                    narrative = analyst.generate_narrative(data)
                    
                    # Alert if severity is high
                    if narrative.severity > 0.7:
                        callback(narrative)
                        
                except Exception as e:
                    print(f"Error in {domain} monitoring: {e}")
            
            await asyncio.sleep(60)  # Check every minute
    
    def execute_action(self, action: Action) -> Observation:
        """
        Execute an approved action.
        
        Only used in SEMI_AUTO or AUTONOMOUS modes.
        """
        if self.config.mode == SwarmMode.ADVISORY:
            return Observation(
                content="Advisory mode - action logged but not executed",
                success=True,
                metadata={"mode": "advisory"},
            )
        
        # Final Judge check
        valid, violations = self.judge.validate(action)
        if not valid:
            return Observation(
                content=None,
                success=False,
                error_message=f"Judge rejected: {violations}",
            )
        
        # Execute via tool
        if action.tool_name in self.tools:
            return self.tools[action.tool_name](**action.parameters)
        
        return Observation(
            content=None,
            success=False,
            error_message=f"Unknown tool: {action.tool_name}",
        )
    
    def get_audit_log(self) -> list[dict]:
        """Get the complete audit log."""
        return self.audit_log
    
    def export_state(self) -> dict:
        """Export complete swarm state for inspection."""
        return {
            "config": {
                "mode": self.config.mode.name,
                "max_concurrent_agents": self.config.max_concurrent_agents,
            },
            "agents": {
                "architect": self.architect.agent_id,
                "analysts": list(self.analysts.keys()),
            },
            "pending_messages": len(self.message_queue),
            "audit_entries": len(self.audit_log),
        }
